bazelbuild/rules_proto

proto/README.md, proto/defs.bzl, proto/private/BUILD, proto/private/dependencies.bzl, proto/private/native.bzl, tests/BUILD, tests/empty.proto
This change is in preparation for `--incompatible_load_proto_rules_from_bzl`.
See https://github.com/bazelbuild/bazel/issues/8891
@hlopko ptal
=> Add migration tag to rules and export some more native symbols

CODEOWNERS
Initial list of owners derived from https://docs.google.com/document/d/1Wai_okIK_NnhNJZai5nkTUvZVHdV5pp1YwNLFtWwpC4/edit?disco=AAAADI3o84E
=> Add CODEOWNERS for rules_proto

proto/defs.bzl, tests/load_from_macro/BUILD, tests/load_from_macro/foo.proto, tests/load_from_macro/tags.bzl
When adding tags to a native cc_library rule that is created through a macro we
were not properly considering the case where the tags came from a different
file and therefore were frozen. This caused an error.
This change was originally submitted by @oquenchil as
https://github.com/bazelbuild/rules_cc/commit/cfe68f6bc79dea602f2f6a767797f94a5904997f
=> Fix immutable frozen set bug in defs.bzl

.gitattributes
It seems like GitHub understands Starlark now, so the .gitattributes
file is no longer needed.
=> Don't set language for Starlark files to Python

WORKSPACE
Updates #43
Fixes #44 
This change makes `rules_proto` compatible with all incompatible changes :)
https://buildkite.com/bazel/rules-proto-plus-bazelisk-migrate/builds/4
=> Update @bazel_toolchains to 2.0.4

proto/private/BUILD.protoc, proto/private/BUILD.protoc_windows, proto/private/BUILD.release, proto/private/dependencies.bzl, proto/private/generate_sums.sh, proto/repositories.bzl
Here's my first stab at implementing issue #35 
I wasn't sure if this code should go here, in https://github.com/protocolbuffers/protobuf or in a separate repo.
This creates a stub workspace with aliases for everything in @com_google_protobuf that either points to the real thing from the protobuf repo, or a binary if it's available. This is mostly working, however I have a few problems:
- It appears aliases don't work for .bzl files. I think we'd either need to copy the .bzl files into this stub workspace, or put the binary aliases directly into the real @com_google_protobuf BUIlD file.
- I'm not sure if this is working for java_proto_libraries. It seems like they may still be depending on the custom built protoc somehow.
=> Use released protoc binaries

proto/BUILD
This allows for `@rules_proto//proto:repositories.bzl` to be usable in [stardoc](https://github.com/bazelbuild/stardoc) docs generation.
=> Added `//proto:repositories` `bzl_library`

proto/private/dependencies.bzl
`rules_proto` is referencing a super outdated version of `rules_java` from 2019 that can cause some confusion if it's not explicitly overridden in your own `WORKSPACE`.
More context: https://github.com/buildfoundation/bazel_rules_detekt/issues/117
=> Update rules_java to HEAD

proto/private/dependencies.bzl
Example failures:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2242#ea9a357d-ed80-4af8-8b4f-93b4dae604e0
=> Update bazel skylib version to prevent failures on newer Bazel versions.

proto/private/dependencies.bzl
This is for CVE-2021-22569 .
See: https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.2
=> Upgrade to protobuf 3.19.2

README.md
Inspired by #47, we can use 'starlark' as annotations for the markdown files.
=> Update code annotations to 'starlark'

proto/private/dependencies.bzl
Issue: https://github.com/bazelbuild/rules_proto/pull/117
According to [zlib](https://zlib.net/) 
```
"Due to the bug fixes, any installations of 1.2.11 should be replaced with 1.2.12."
```
=> [Zlib] update zlib version to zlib-1.2.12

proto/private/BUILD.release, proto/private/dependencies.bzl
And add prebuilt protoc binaries for Apple silicon.
=> Update protobuf to 3.20.0

WORKSPACE
Ugrade bazel-toolchain to 5.1.2 to use constraints values from `@platforms`
https://github.com/bazelbuild/continuous-integration/issues/1404
=> migrating to usage of rbe_preconfig and remove bazel-toolchains

proto/private/dependencies.bzl
This is my first contribution to `rules_proto` -- greatly appreciate your patience! I've already signed the CLA on my own behalf.
Fixes https://github.com/bazelbuild/rules_proto/issues/95.
This bumps `rules_cc` to (as of writing) HEAD, authored ~21 days ago:
https://github.com/bazelbuild/rules_cc/commit/2f8c04c04462ab83c545ab14c0da68c3b4c96191
To verify, I:
- reproduced the error described in https://github.com/erenon/bazel_clang_tidy/issues/8
- Updated `bazel_clang_tidy`'s version of `rules_proto` to this commit, and verified that the error no longer occurred:
```
ouguoc:~/bazel_clang_tidy$ bazel build //example:app     --aspects clang_tidy/clang_tidy.bzl%clang_tidy_aspect     --output_groups=report
INFO: Analyzed target //example:app (0 packages loaded, 0 targets configured).
INFO: …
```
=> Bump rules_cc to 2f8c04c

proto/private/dependencies.bzl
For whatever reason these are incorrect and broken at the release tag, and a new release should be cut with these values.
=> fix jar shasums for protobuf java/util

proto/private/BUILD.release
Fixes https://github.com/bazelbuild/rules_proto/issues/121.
This exposes the `@com_google_protobuf//:protobuf_lite` target, which is a common dependency.
To test this, I:
- built the target directly from `rules_proto`'s own workspace:
```
ouguoc:~/rules_proto$ bazel build @com_google_protobuf//:protobuf_lite
INFO: Analyzed target @com_google_protobuf//:protobuf_lite (38 packages loaded, 440 targets configured).
INFO: Found 1 target...
Target @com_github_protocolbuffers_protobuf//:protobuf_lite up-to-date:
bazel-bin/external/com_github_protocolbuffers_protobuf/libprotobuf_lite.a
bazel-bin/external/com_github_protocolbuffers_protobuf/libprotobuf_lite.so
INFO: Elapsed time: 1.201s, Critical Path: 0.13s
INFO: 3 processes: 2 internal, 1 linux-sandbox.
INFO: Build completed successfully, 3 …
```
=> Add protobuf_lite target to protobuf_workspace

MODULE.bazel, proto/private/dependencies.bzl
Updates protobuf version to 21.7 and fixes security issues mentioned in #148
Unfortunately not all mirror links are available for 21.7
=> Update protobuf to v21.7

MODULE.bazel, proto/private/dependencies.bzl
This intends to be solving issue #10965 and #2530. It just updates bazel skylib to version 1.3.0.
=> Changing bazel skylib version from 1.1.1 to 1.3.0

.pre-commit-config.yaml
This matches the Bazel recommendation from https://github.com/bazel-contrib/rules-template for configuring an optional, client-side automation for formatting BUILD/bzl files before sending a PR.
It has been found to save a bunch of time for contributors who otherwise trip over the server-side CI check and have to do an extra iteration to get their PR green.
I imagine Googlers are already relying on some Piper feature to do the equivalent when they work on this code, so they haven't noticed the deficiency.
=> chore: add a pre-commit hook config.

.bcr/README.md, .bcr/metadata.template.json, .bcr/source.template.json, .gitattributes, .github/workflows/release.yml, .github/workflows/release_prep.sh, CONTRIBUTING.md, MODULE.bazel
This also fixes our current dependency on GitHub archives which are not guaranteed to be stable, https://github.com/bazelbuild/bazel-central-registry/pull/332/files#diff-7288b02983f19cbe12177d5f193a6bfc533e352fc44fbe12cdb93e1c8c28dcd1R4 which requires a special 'skip-url-stability-check' label on the BCR PR
Instead, we run 'git archive' to create the release artifact. We can now prune the tests/ folder from that artifact, which lets us remove an exclusion from the presubmit as well.
Fixes #188
=> chore: automate releases

.github/workflows/ci.bazelrc
In https://github.com/bazel-contrib/.github/blob/master/.github/workflows/release_ruleset.yaml#L42 we assume this file will exist in the repo
=> chore: add missing file needed by release automation

.bcr/config.yml
Now that releases are automated, the release doesn't have an author, so the app can't figure out whose fork of bazel-central-registry the PR should originate from.
This will fix the error from publishing 6.0.0-rc0 to the BCR.
=> chore: add config for Publish to BCR app

.bcr/presubmit.yml
This fixes the bcr presubmit. It was failing because the tests directory is excluded from the release archive.
See: https://github.com/bazelbuild/bazel-central-registry/pull/1174/commits/f4c8ec3d07ad5206d665171bc638b98f982b92c5
=> fix: presubmit does not have access to tests

MODULE.bazel, MODULE.bazel.lock, proto/repositories.bzl
https://github.com/bazelbuild/rules_proto/commits/main/ has been red since Feb 12.
We need to pick up https://github.com/bazel-contrib/bazel_features/pull/33 to fix it.
Allows the 6.0.0 release to complete.
=> chore: fix stardoc targets

MODULE.bazel, MODULE.bazel.lock, dev_deps.bzl, proto/repositories.bzl
This is used in tools/file_concat which is part of proto_descriptor_set. I think this worked before because it was implicitly imported by bazel
=> Make rules_cc a production dep

MODULE.bazel.lock, WORKSPACE, proto/BUILD, proto/repositories.bzl
This ensures that existing consumers of `rules_proto`'s toolchain type keep working with newer versions of protobuf (as forced by Bazel 8).
=> Alias protobuf toolchain_type
